const products = [
  {
    id: 1,
    name: "Vintage",
    category: "chairs",
    price: 220,
    available: true,
    soldItems: 50,
    discount: 10,
    new: false,
    img: {
      img1: "../data/products/chair/chair1/chair1_1.jpg",
      img2: "../data/products/chair/chair1/chair1_2.jpg",
      img3: "../data/products/chair/chair1/chair1_3.jpg",
    },
    code: 666559,
    desc: "The chair is made of oak, its design is permeated by fluid, organic forms, combining strong curves with exceptional lightness. As a result, we got a minimalist design that optimizes comfort and is focused on man and his movements, without lacking aesthetics and characteristic details.",
    dimensions: {
      width: "62",
      height: "80",
      length: "39",
    },
    hoverImg: "../data/products/chair/chair1/chair1_hover.jpg",
  },
  {
    id: 2,
    name: "Hibrid",
    category: "chairs",
    price: 1399,
    available: true,
    soldItems: 33,
    discount: 0,
    new: true,
    img: {
      img1: "../data/products/chair/chair2/chair2_1.jpg",
      img2: "../data/products/chair/chair2/chair2_2.jpg",
      img3: "../data/products/chair/chair2/chair2_3.jpg",
    },
    code: 999111,
    desc: "This luxury hybrid armchair offers unparalleled seating comfort thanks to its robust frame and soft upholstery. It is characterized by solid legs, made using traditional carpentry techniques, and large armrests and a seat cushion, upholstered in a range of soft fabrics, creating a sense of comfort and lightness in any environment.",
    dimensions: {
      width: "84",
      height: "82",
      length: "96",
    },
    hoverImg: "../data/products/chair/chair2/chair2_hover.jpg",
  },
  {
    id: 3,
    name: "Jack",
    category: "chairs",
    price: 1199,
    available: true,
    soldItems: 44,
    discount: 10,
    new: false,
    img: {
      img1: "../data/products/chair/chair3/chair3_1.jpg",
      img2: "../data/products/chair/chair3/chair3_2.jpg",
      img3: "../data/products/chair/chair3/chair3_3.jpg",
    },
    code: 357159,
    desc: "The luxurious shapes that characterize the Jack chair are beautiful from every angle. The clean lines of this collection are inspired by Scandinavian modernism. With cushions wrapped in upholstery knitted in Belgium, every detail has been carefully designed and crafted to ensure comfort and elegance when enjoying the outdoors.",
    dimensions: {
      width: "74",
      height: "73",
      length: "90",
    },
    hoverImg: "../data/products/chair/chair3/chair3_hover.jpg",
  },
  {
    id: 4,
    name: "Cover",
    category: "chairs",
    price: 1345,
    available: true,
    soldItems: 20,
    discount: 0,
    new: true,
    img: {
      img1: "../data/products/chair/chair4/chair4_1.jpg",
      img2: "../data/products/chair/chair4/chair4_2.jpg",
      img3: "../data/products/chair/chair4/chair4_3.jpg",
    },
    code: 336699,
    desc: "Invoking the values of honest craftsmanship and Scandinavian materiality, the Cover chair is an elegant perspective on the timeless wooden armchair. With its curved backrest and folded armrests, Cover explores the possibilities of wood veneer, paired with deep comfort, a modern expression and a solid wood base. You can use the Cover chair in the living room, hallway or bedroom, as well as in restaurants, offices or educational institutions.",
    dimensions: {
      width: "56",
      height: "72",
      length: "49",
    },
    hoverImg: "../data/products/chair/chair4/chair4_hover.jpg",
  },
  {
    id: 5,
    name: "Fiber",
    category: "chairs",
    price: 999,
    available: true,
    soldItems: 55,
    discount: 0,
    new: false,
    img: {
      img1: "../data/products/chair/chair5/chair5_1.jpg",
      img2: "../data/products/chair/chair5/chair5_2.jpg",
      img3: "../data/products/chair/chair5/chair5_3.jpg",
    },
    code: 595482,
    desc: "This chair is perfect for people who like minimalism with style. The seat part is made of plastic and wood fibers with a matte and tactile surface.",
    dimensions: {
      width: "74",
      height: "73",
      length: "90",
    },
    hoverImg: "../data/products/chair/chair5/chair5_hover.jpg",
  },
  {
    id: 6,
    name: "Laura",
    category: "sofas",
    price: 1200,
    available: true,
    soldItems: 15,
    discount: 0,
    new: false,
    img: {
      img1: "../data/products/sofa/sofa1/sofa1_1.jpg",
      img2: "../data/products/sofa/sofa1/sofa1_2.jpg",
      img3: "../data/products/sofa/sofa1/sofa1_3.jpg",
    },
    code: 777567,
    desc: "It is designed like a blank painting canvas, prepared to receive a personal touch, and the backrest in the form of an envelope is ready to hug the cushions of your choice.",
    dimensions: {
      width: "91",
      height: "74",
      length: "211",
    },
    hoverImg: "../data/products/sofa/sofa1/sofa1_hover.jpg",
  },
  {
    id: 7,
    name: "Double sofa",
    category: "sofas",
    price: 1150,
    available: true,
    soldItems: 38,
    discount: 0,
    new: true,
    img: {
      img1: "../data/products/sofa/sofa2/sofa2_1.jpg",
      img2: "../data/products/sofa/sofa2/sofa2_2.jpg",
      img3: "../data/products/sofa/sofa2/sofa2_3.jpg",
    },
    code: 484899,
    desc: "It is a design that is ready to embrace and relax you, it simply invites you to sit in it and test the comfort that is read already on the visual level. This sofa offers endless ways to combine and adapt it for different spaces.",
    dimensions: {
      width: "91",
      height: "76",
      length: "140",
    },
    hoverImg: "../data/products/sofa/sofa2/sofa2_hover.jpg",
  },
  {
    id: 8,
    name: "The King",
    category: "sofas",
    price: 1550,
    available: true,
    soldItems: 60,
    discount: 0,
    new: false,
    img: {
      img1: "../data/products/sofa/sofa3/sofa3_1.jpg",
      img2: "../data/products/sofa/sofa3/sofa3_2.jpg",
      img3: "../data/products/sofa/sofa3/sofa3_3.jpg",
    },
    code: 111212,
    desc: "The King modular sofa is a brilliant, modular design with sculptural lines that can be adapted to your individual space and taste, while with its modular elements, hidden through the subtle details of the front profile, it is paired with deep comfort and a soft seat.",
    dimensions: {
      width: "107",
      height: "70",
      length: "279",
    },
    hoverImg: "../data/products/sofa/sofa3/sofa3_hover.jpg",
  },
  {
    id: 9,
    name: "Grand table",
    category: "tables",
    price: 1650,
    available: true,
    soldItems: 54,
    discount: 0,
    new: true,
    img: {
      img1: "../data/products/table/table1/table1_1.jpg",
      img2: "../data/products/table/table1/table1_2.jpg",
      img3: "../data/products/table/table1/table1_3.jpg",
    },
    code: 666655,
    desc: "With slender legs, and beveled details to connect to the useful surface, the Air seems to stand without any effort. Strong and slender, infinitely simple, weightless in appearance.",
    dimensions: {
      width: "100",
      height: "80",
      length: "200",
    },
    hoverImg: "../data/products/table/table1/table1_hover.jpg",
  },
  {
    id: 10,
    name: "Ahil",
    category: "tables",
    price: 1350,
    available: true,
    soldItems: 62,
    discount: 0,
    new: false,
    img: {
      img1: "../data/products/table/table2/table2_1.jpg",
      img2: "../data/products/table/table2/table2_2.jpg",
      img3: "../data/products/table/table2/table2_3.jpg",
    },
    code: 876521,
    desc: "The round dining table from the Bok collection made of solid oak is an ideal option for an adaptable dining room in a smaller space. With an internal extension, the round table can easily be converted into a multi-person table in just a few steps",
    dimensions: {
      width: "100",
      height: "50",
      length: "100",
    },
    hoverImg: "../data/products/table/table2/table2_hover.jpg",
  },
  {
    id: 11,
    name: "Aurora",
    category: "chairs",
    price: 799,
    available: true,
    soldItems: 28,
    discount: 10,
    new: true,
    img: {
      img1: "../data/products/chair/chair6/chair6_1.jpg",
      img2: "../data/products/chair/chair6/chair6_2.jpg",
      img3: "../data/products/chair/chair6/chair6_3.jpg",
    },
    code: 123456,
    desc: "The Aurora chair features a sleek and sophisticated design, combining comfort with modern aesthetics. Its curved backrest provides excellent lumbar support, and the high-quality upholstery adds a touch of elegance to any space.",
    dimensions: {
      width: "89",
      height: "71",
      length: "79",
    },
    hoverImg: "../data/products/chair/chair6/chair6_hover.jpg",
  },
  {
    id: 12,
    name: "Serenity",
    category: "chairs",
    price: 1599,
    available: true,
    soldItems: 10,
    discount: 0,
    new: false,
    img: {
      img1: "../data/products/chair/chair7/chair7_1.jpg",
      img2: "../data/products/chair/chair7/chair7_2.jpg",
      img3: "../data/products/chair/chair7/chair7_3.jpg",
    },
    code: 987654,
    desc: "The Serenity chair offers the ultimate relaxation experience with its plush cushioning and ergonomic design. It's perfect for cozying up with a book or enjoying a quiet evening at home.",
    dimensions: {
      width: "80",
      height: "95",
      length: "75",
    },
    hoverImg: "../data/products/chair/chair7/chair7_hover.jpg",
  },
  {
    id: 13,
    name: "Nova",
    category: "chairs",
    price: 599,
    available: false,
    soldItems: 50,
    discount: 0,
    new: false,
    img: {
      img1: "../data/products/chair/chair8/chair8_1.jpg",
      img2: "../data/products/chair/chair8/chair8_2.jpg",
      img3: "../data/products/chair/chair8/chair8_3.jpg",
    },
    code: 246810,
    desc: "Embrace the charm of the past with the Nova chair. Its vintage-inspired design and vibrant colors add a touch of nostalgia to any room. Made with durable materials, it combines style and functionality effortlessly.",
    dimensions: {
      width: "64",
      height: "77",
      length: "58",
    },
    hoverImg: "../data/products/chair/chair8/chair8_hover.jpg",
  },
  {
    id: 14,
    name: "Zenith",
    category: "chairs",
    price: 899,
    available: true,
    soldItems: 40,
    discount: 5,
    new: true,
    img: {
      img1: "../data/products/chair/chair9/chair9_1.jpg",
      img2: "../data/products/chair/chair9/chair9_2.jpg",
      img3: "../data/products/chair/chair9/chair9_3.jpg",
    },
    code: 135791,
    desc: "The Zenith chair exudes timeless elegance with its refined design and high-quality craftsmanship. It features a solid wood frame and plush cushioning for maximum comfort. Enhance the beauty of your space with this sophisticated piece.",
    dimensions: {
      width: "70",
      height: "85",
      length: "65",
    },
    hoverImg: "../data/products/chair/chair9/chair9_hover.jpg",
  },
  {
    id: 15,
    name: "Velvet",
    category: "chairs",
    price: 1299,
    available: true,
    soldItems: 15,
    discount: 0,
    new: false,
    img: {
      img1: "../data/products/chair/chair10/chair10_1.jpg",
      img2: "../data/products/chair/chair10/chair10_2.jpg",
      img3: "../data/products/chair/chair10/chair10_3.jpg",
    },
    code: 864209,
    desc: "Indulge in luxury with the Velvet chair. Its sumptuous velvet upholstery and exquisite detailing make it a standout piece in any room. Sit back and relax in opulent comfort with this stunning chair.",
    dimensions: {
      width: "76",
      height: "92",
      length: "68",
    },
    hoverImg: "../data/products/chair/chair10/chair10_hover.jpg",
  },
  {
    id: 16,
    name: "Cosy",
    category: "sofas",
    price: 1899,
    available: false,
    soldItems: 20,
    discount: 8,
    new: true,
    img: {
      img1: "../data/products/sofa/sofa4/sofa4_1.jpg",
      img2: "../data/products/sofa/sofa4/sofa4_2.jpg",
      img3: "../data/products/sofa/sofa4/sofa4_3.jpg",
    },
    code: 753421,
    desc: "The Cosy sofa is designed for maximum comfort and relaxation. Its plush cushions and generous seating space create an inviting atmosphere in your living room. Enjoy cozy evenings with your loved ones on this stylish sofa.",
    dimensions: {
      width: "95",
      height: "78",
      length: "220",
    },
    hoverImg: "../data/products/sofa/sofa4/sofa4_hover.jpg",
  },
  {
    id: 17,
    name: "Sleek",
    category: "sofas",
    price: 1499,
    available: true,
    soldItems: 35,
    discount: 0,
    new: false,
    img: {
      img1: "../data/products/sofa/sofa5/sofa5_1.jpg",
      img2: "../data/products/sofa/sofa5/sofa5_2.jpg",
      img3: "../data/products/sofa/sofa5/sofa5_3.jpg",
    },
    code: 987123,
    desc: "With its clean lines and minimalist design, the Sleek sofa adds a touch of modern sophistication to your living space. Its sleek profile and high-quality materials make it a standout piece that combines style and comfort seamlessly.",
    dimensions: {
      width: "88",
      height: "72",
      length: "190",
    },
    hoverImg: "../data/products/sofa/sofa5/sofa5_hover.jpg",
  },
  {
    id: 18,
    name: "Enigma",
    category: "sofas",
    price: 2599,
    available: true,
    soldItems: 12,
    discount: 15,
    new: false,
    img: {
      img1: "../data/products/sofa/sofa6/sofa6_1.jpg",
      img2: "../data/products/sofa/sofa6/sofa6_2.jpg",
      img3: "../data/products/sofa/sofa6/sofa6_3.jpg",
    },
    code: 246813,
    desc: "Indulge in the lap of luxury with the Enigma sofa. It features exquisite detailing, premium upholstery, and unparalleled comfort. Transform your living room into a haven of elegance with this opulent piece.",
    dimensions: {
      width: "102",
      height: "80",
      length: "230",
    },
    hoverImg: "../data/products/sofa/sofa6/sofa6_hover.jpg",
  },
  {
    id: 19,
    name: "Ember",
    category: "tables",
    price: 899,
    available: true,
    soldItems: 50,
    discount: 5,
    new: true,
    img: {
      img1: "../data/products/table/table3/table3_1.jpg",
      img2: "../data/products/table/table3/table3_2.jpg",
      img3: "../data/products/table/table3/table3_3.jpg",
    },
    code: 135790,
    desc: "Embrace contemporary design with the Ember table. Its sleek lines and minimalist aesthetics make it a perfect addition to any modern living space. Crafted with high-quality materials, this table combines style and functionality effortlessly.",
    dimensions: {
      width: "120",
      height: "75",
      length: "60",
    },
    hoverImg: "../data/products/table/table3/table3_hover.jpg",
  },
  {
    id: 20,
    name: "Veritas",
    category: "tables",
    price: 1299,
    available: true,
    soldItems: 18,
    discount: 0,
    new: false,
    img: {
      img1: "../data/products/table/table4/table4_1.jpg",
      img2: "../data/products/table/table4/table4_2.jpg",
      img3: "../data/products/table/table4/table4_3.jpg",
    },
    code: 369852,
    desc: "Add a touch of elegance to your dining room with the Veritas table. Crafted from solid oak, this table showcases the beauty of natural wood grain. Its timeless design and sturdy construction make it a lasting piece of furniture.",
    dimensions: {
      width: "150",
      height: "80",
      length: "90",
    },
    hoverImg: "../data/products/table/table4/table4_hover.jpg",
  },
  {
    id: 21,
    name: "Harmony",
    category: "tables",
    price: 1599,
    available: true,
    soldItems: 25,
    discount: 12,
    new: true,
    img: {
      img1: "../data/products/table/table5/table5_1.jpg",
      img2: "../data/products/table/table5/table5_2.jpg",
      img3: "../data/products/table/table5/table5_3.jpg",
    },
    code: 258741,
    desc: "Experience the perfect blend of style and functionality with the Harmony table. Its sleek design and smooth lines create a harmonious atmosphere in any dining space. Crafted with high-quality materials, this table is built to last.",
    dimensions: {
      width: "180",
      height: "75",
      length: "90",
    },
    hoverImg: "../data/products/table/table5/table5_hover.jpg",
  },
  {
    id: 22,
    name: "Reflection",
    category: "tables",
    price: 899,
    available: true,
    soldItems: 40,
    discount: 8,
    new: false,
    img: {
      img1: "../data/products/table/table6/table6_1.jpg",
      img2: "../data/products/table/table6/table6_2.jpg",
      img3: "../data/products/table/table6/table6_3.jpg",
    },
    code: 987654,
    desc: "Create a captivating dining experience with the Reflection table. Its mirrored surface and sleek design add a touch of elegance to any space. This table is perfect for those who appreciate contemporary aesthetics.",
    dimensions: {
      width: "160",
      height: "76",
      length: "80",
    },
    hoverImg: "../data/products/table/table6/table6_hover.jpg",
  },
  {
    id: 23,
    name: "Beatrice",
    category: "chairs",
    price: 680,
    available: true,
    soldItems: 6,
    discount: 0,
    new: false,
    img: {
      img1: "../data/products/chair/chair11/chair11_1.jpg",
      img2: "../data/products/chair/chair11/chair11_2.jpg",
      img3: "../data/products/chair/chair11/chair11_3.jpg",
    },
    code: 884209,
    desc: "Experience pure comfort with the Beatrice Chair. Its sumptuous velvet upholstery and exquisite detailing create a standout piece for any room. Sink into opulent comfort and relax in style with this stunning chair",
    dimensions: {
      width: "76",
      height: "92",
      length: "68",
    },
    hoverImg: "../data/products/chair/chair11/chair11_hover.jpg",
  },
  {
    id: 24,
    name: "Clasic",
    category: "chairs",
    price: 300,
    available: true,
    soldItems: 20,
    discount: 0,
    new: false,
    img: {
      img1: "../data/products/chair/chair12/chair12_1.jpg",
      img2: "../data/products/chair/chair12/chair12_2.jpg",
      img3: "../data/products/chair/chair12/chair12_3.jpg",
    },
    code: 666559,
    desc: "The chair is made of oak, its design is permeated by fluid, organic forms, combining strong curves with exceptional lightness. As a result, we got a minimalist design that optimizes comfort and is focused on man and his movements, without lacking aesthetics and characteristic details.",
    dimensions: {
      width: "62",
      height: "80",
      length: "39",
    },
    hoverImg: "../data/products/chair/chair12/chair12_hover.jpg",
  },
];

const getAllProducts = () => {
  return products;
};
//categories
const getChairs = () => {
  const allChairs = products.filter((product) => product.category == "chairs");
  return allChairs.length > 0 ? allChairs : null;
};
const getTables = () => {
  const allTables = products.filter((product) => product.category == "tables");
  return allTables.length > 0 ? allTables : null;
};
const getSofas = () => {
  const allSofas = products.filter((product) => product.category == "sofas");
  return allSofas.length > 0 ? allSofas : null;
};

const getProductById = (ID) => {
  const findProduct = products.filter((product) => product.id == ID);
  return findProduct.length > 0 ? findProduct[0] : null;
};
const getMostPopular = () => {
  const popular = products;
  return popular.sort(function (a, b) {
      return b.soldItems - a.soldItems;
    })
    .slice(0, 5);
};
module.exports = {
  getAllProducts,
  getChairs,
  getTables,
  getSofas,
  getProductById,
  getMostPopular,
};
